# Generated by Django 4.2.11 on 2024-03-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Merchant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("merchantmen", models.CharField(max_length=30, verbose_name="姓名")),
                (
                    "email",
                    models.EmailField(max_length=30, unique=True, verbose_name="邮箱"),
                ),
                ("password", models.CharField(max_length=128, verbose_name="密码")),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
                "db_table": "mc_users",
            },
        ),
    ]
