# Generated by Django 4.2.11 on 2024-03-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="merchant",
            options={"verbose_name": "商家", "verbose_name_plural": "商家"},
        ),
        migrations.AddField(
            model_name="merchant",
            name="mobile",
            field=models.CharField(default=None, max_length=11, verbose_name="手机号"),
        ),
    ]
