# Generated by Django 4.2.11 on 2024-03-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0002_alter_merchant_options_merchant_mobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchant",
            name="email",
            field=models.EmailField(max_length=125, unique=True, verbose_name="邮箱"),
        ),
    ]
