# Generated by Django 4.2.11 on 2024-03-29 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
        ("merchant", "0003_alter_merchant_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchant",
            name="shop",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shops",
                to="shop.shop",
                verbose_name="店铺",
            ),
        ),
    ]
