# Generated by Django 4.2.11 on 2024-03-30 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_goods_shop_goods"),
        ("merchant", "0004_merchant_shop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchant",
            name="shop",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shops",
                to="shop.shop",
                verbose_name="店铺",
            ),
        ),
    ]
