# Generated by Django 4.2.11 on 2024-04-02 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0005_alter_merchant_shop"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="merchant",
            name="shop",
        ),
    ]
