# Generated by Django 4.2.11 on 2024-03-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shop_name", models.CharField(max_length=30, verbose_name="店名")),
                (
                    "mark",
                    models.CharField(
                        choices=[("1", 1), ("2", 2), ("3", 3), ("4", 4), ("5", 5)],
                        max_length=10,
                        verbose_name="评分",
                    ),
                ),
                ("adders", models.CharField(max_length=200, verbose_name="地址")),
                ("phone", models.CharField(max_length=15, verbose_name="电话")),
            ],
            options={
                "verbose_name": "店铺",
                "verbose_name_plural": "店铺",
                "db_table": "shops",
            },
        ),
    ]
