# Generated by Django 4.2.11 on 2024-04-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_alter_goods_options_alter_goods_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="shop_name",
            field=models.CharField(max_length=30, unique=True, verbose_name="店名"),
        ),
    ]
