# Generated by Django 4.2.11 on 2024-04-02 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0006_remove_merchant_shop"),
        ("shop", "0004_alter_shop_shop_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shop",
            name="goods",
        ),
        migrations.AddField(
            model_name="goods",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.shop",
                verbose_name="Shop",
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="merchant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="merchant.merchant",
                verbose_name="merchant",
            ),
        ),
    ]
