# Generated by Django 4.2.11 on 2024-04-11 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("consumer", "0005_orders_browser"),
        ("shop", "0008_rename_goodstype_shopstype_remove_goods_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="goods",
            name="browsers",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goods",
                to="consumer.browser",
                verbose_name="浏览记录",
            ),
        ),
        migrations.AddField(
            model_name="goods",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goods",
                to="consumer.orders",
                verbose_name="订单",
            ),
        ),
    ]
