# Generated by Django 4.2.11 on 2024-04-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_remove_goods_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="mark",
            field=models.CharField(
                choices=[("1", 1), ("2", 2), ("3", 3), ("4", 4), ("5", 5)],
                default=5,
                max_length=10,
                verbose_name="评分",
            ),
        ),
    ]
