# Generated by Django 4.2.11 on 2024-03-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consumer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consumer",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="邮箱"),
        ),
    ]
