# Generated by Django 4.2.11 on 2024-03-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consumer", "0002_alter_consumer_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consumer",
            name="mobile",
            field=models.CharField(max_length=11, verbose_name="手机号"),
        ),
    ]
