# Generated by Django 4.2.11 on 2024-04-11 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("consumer", "0005_orders_browser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="fk_goods",
        ),
        migrations.AddField(
            model_name="comment",
            name="fk_orders",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="consumer.orders",
                verbose_name="评论所属订单",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orders",
            name="is_comment",
            field=models.BooleanField(default=False, verbose_name="Is Comment"),
        ),
    ]
