# Generated by Django 4.2.11 on 2024-04-11 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_remove_goods_order"),
        ("merchant", "0007_alter_merchant_mobile"),
        ("consumer", "0006_remove_comment_fk_goods_comment_fk_orders_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orders",
            options={"verbose_name": "订单", "verbose_name_plural": "订单"},
        ),
        migrations.AddField(
            model_name="orders",
            name="goods",
            field=models.ManyToManyField(
                related_name="orders", to="shop.goods", verbose_name="goods"
            ),
        ),
        migrations.AddField(
            model_name="orders",
            name="merchant",
            field=models.ForeignKey(
                default= 1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="merchant.merchant",
            ),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name="orders",
            table="orders",
        ),
    ]
