# Generated by Django 4.2.11 on 2024-04-11 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_remove_goods_order"),
        ("consumer", "0007_alter_orders_options_orders_goods_orders_merchant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="merchant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="shop.shop",
            ),
        ),
    ]
