# Generated by Django 4.2.11 on 2024-04-11 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consumer", "0008_alter_orders_merchant"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orders",
            old_name="merchant",
            new_name="shop",
        ),
    ]
