# Generated by Django 4.2.11 on 2024-04-11 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_remove_goods_order"),
        ("consumer", "0009_rename_merchant_orders_shop"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="fk_orders",
        ),
        migrations.AddField(
            model_name="comment",
            name="fk_shop",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="shop.shop",
            ),
        ),
    ]
